from configurations.analytical_pattern_templates.load_dataset import LOAD_DATASET_TEMPLATE
from configurations.analytical_pattern_templates.register_dataset import REGISTER_DATASET_TEMPLATE

__all__ = ["LOAD_DATASET_TEMPLATE", "REGISTER_DATASET_TEMPLATE"]